// js/sampleData/sampleShopSphere.js

/** Sample Data for ShopSphere (eCommerce Platform) **/

// Define all sample data arrays for ShopSphere FIRST
const sampleProjectManagersDataShopSphere = [
  { pmId: 'pmSS001', pmName: 'Marcus Timeline', attributes: {} },
  { pmId: 'pmSS002', pmName: 'Chloe Scope', attributes: {} },
  { pmId: 'pmSS003', pmName: 'Kenji Velocity', attributes: {} },
];

const sampleSeniorManagersDataShopSphere = [
  {
    seniorManagerId: 'srMgrSS1',
    seniorManagerName: 'Sarah Chen (VP, Core Platform)',
    attributes: {},
  },
  {
    seniorManagerId: 'srMgrSS2',
    seniorManagerName: 'David Lee (VP, Retail Experience)',
    attributes: {},
  },
];

const shopSphereSDMsData = [
  {
    sdmId: 'sdmSS1',
    sdmName: 'Anil Gupta (Platform Infra)',
    seniorManagerId: 'srMgrSS1',
    attributes: {},
  },
  {
    sdmId: 'sdmSS2',
    sdmName: 'Maria Rodriguez (Search & Discovery)',
    seniorManagerId: 'srMgrSS1',
    attributes: {},
  },
  {
    sdmId: 'sdmSS3',
    sdmName: 'Kenji Watanabe (Checkout & Payments)',
    seniorManagerId: 'srMgrSS1',
    attributes: {},
  },
  {
    sdmId: 'sdmSS4',
    sdmName: 'Emily White (Web & Mobile Apps)',
    seniorManagerId: 'srMgrSS2',
    attributes: {},
  },
  {
    sdmId: 'sdmSS5',
    sdmName: 'James Brown (Seller Solutions)',
    seniorManagerId: 'srMgrSS2',
    attributes: {},
  },
  {
    sdmId: 'sdmSS6',
    sdmName: 'Li Wang (Data & Analytics)',
    seniorManagerId: 'srMgrSS2',
    attributes: {},
  },
];

const shopSpherePMTsData = [
  { pmtId: 'pmtSS1', pmtName: 'Olivia Hayes (Core Platform PM)', attributes: {} },
  { pmtId: 'pmtSS2', pmtName: 'Ben Carter (Search & Reco PM)', attributes: {} },
  { pmtId: 'pmtSS3', pmtName: 'Priya Singh (Checkout PM)', attributes: {} },
  { pmtId: 'pmtSS4', pmtName: 'Alex Johnson (Retail Apps PM)', attributes: {} },
  { pmtId: 'pmtSS5', pmtName: 'Zoe Kim (Seller PM)', attributes: {} },
  { pmtId: 'pmtSS6', pmtName: 'Daniel Chen (Analytics PM)', attributes: {} },
];

const sampleAllKnownEngineersShopSphere = [
  // Team SS1: Atlas Infra (Platform)
  {
    engineerId: 'engSS1',
    name: 'Anil Gupta',
    level: 5,
    currentTeamId: 'teamSS1',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['System Architecture', 'AWS', 'Kubernetes', 'SRE'],
      yearsOfExperience: 10,
    },
  },
  {
    engineerId: 'engSS2',
    name: 'Bethany Smith',
    level: 4,
    currentTeamId: 'teamSS1',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Kafka', 'Service Mesh', 'Go', 'Observability'],
      yearsOfExperience: 7,
    },
  },
  {
    engineerId: 'engSS3',
    name: 'Carlos Diaz',
    level: 3,
    currentTeamId: 'teamSS1',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Terraform', 'CI/CD', 'Python', 'Security'],
      yearsOfExperience: 4,
    },
  },
  {
    engineerId: 'engSS4',
    name: 'Diana Wells',
    level: 2,
    currentTeamId: 'teamSS1',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['AWS CDK', 'Monitoring', 'Scripting'],
      yearsOfExperience: 2,
    },
  },
  // Team SS2: Search Strikers
  {
    engineerId: 'engSS5',
    name: 'Maria Rodriguez',
    level: 5,
    currentTeamId: 'teamSS2',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Search Architecture', 'Elasticsearch', 'NLP', 'Team Leadership'],
      yearsOfExperience: 11,
    },
  },
  {
    engineerId: 'engSS6',
    name: 'Evan Li',
    level: 4,
    currentTeamId: 'teamSS2',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Search Relevance', 'Vector Databases', 'Python', 'ML'],
      yearsOfExperience: 6,
    },
  },
  {
    engineerId: 'engSS7',
    name: 'Fiona Chen',
    level: 3,
    currentTeamId: 'teamSS2',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Elasticsearch', 'Java (Spring)', 'Indexing Pipelines'],
      yearsOfExperience: 4,
    },
  },
  {
    engineerId: 'engSS8',
    name: 'George Kims',
    level: 2,
    currentTeamId: 'teamSS2',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Search UI', 'React', 'A/B Testing'],
      yearsOfExperience: 2,
    },
  },
  // Team SS3: Discovery Crew (Recommendations)
  {
    engineerId: 'engSS9',
    name: 'Hannah Davis',
    level: 4,
    currentTeamId: 'teamSS3',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Recommendation Systems', 'ML', 'Spark', 'Python'],
      yearsOfExperience: 7,
    },
  },
  {
    engineerId: 'engSS10',
    name: 'Ivan Petrov',
    level: 3,
    currentTeamId: 'teamSS3',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['MLOps', 'Kubeflow', 'AWS Sagemaker', 'Data Pipelines'],
      yearsOfExperience: 5,
    },
  },
  {
    engineerId: 'engSS11',
    name: 'Julia Romano',
    level: 3,
    currentTeamId: 'teamSS3',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Feature Engineering', 'SQL', 'Python', 'Analytics'],
      yearsOfExperience: 3,
    },
  },
  // Team SS4: Checkout Kings (Checkout)
  {
    engineerId: 'engSS12',
    name: 'Kenji Watanabe',
    level: 5,
    currentTeamId: 'teamSS4',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['System Design', 'Java', 'High Availability', 'Payments'],
      yearsOfExperience: 12,
    },
  },
  {
    engineerId: 'engSS13',
    name: 'Leo Martinez',
    level: 4,
    currentTeamId: 'teamSS4',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['API Design', 'Microservices', 'Java', 'PostgreSQL'],
      yearsOfExperience: 6,
    },
  },
  {
    engineerId: 'engSS14',
    name: 'Mona Amini',
    level: 3,
    currentTeamId: 'teamSS4',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Frontend', 'React', 'State Management', 'Accessibility'],
      yearsOfExperience: 4,
    },
  },
  {
    engineerId: 'engSS15',
    name: 'Nate Jacobs',
    level: 2,
    currentTeamId: 'teamSS4',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Java', 'JUnit', 'SQL'],
      yearsOfExperience: 2,
    },
  },
  // Team SS5: FinOps (Payments)
  {
    engineerId: 'engSS16',
    name: 'Oscar Wilde',
    level: 4,
    currentTeamId: 'teamSS5',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Payment Systems', 'PCI Compliance', 'Stripe API', 'FinTech'],
      yearsOfExperience: 8,
    },
  },
  {
    engineerId: 'engSS17',
    name: 'Patel Kumar',
    level: 3,
    currentTeamId: 'teamSS5',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Fraud Detection', 'ML', 'Python', 'SQL'],
      yearsOfExperience: 5,
    },
  },
  {
    engineerId: 'engSS18',
    name: 'Quincy Jones',
    level: 3,
    currentTeamId: 'teamSS5',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Backend API', 'Go', 'Database', 'Security'],
      yearsOfExperience: 4,
    },
  },
  // Team SS6: UIE Wizards (Web/Mobile)
  {
    engineerId: 'engSS19',
    name: 'Emily White',
    level: 5,
    currentTeamId: 'teamSS6',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Frontend Architecture', 'React', 'React Native', 'Performance'],
      yearsOfExperience: 10,
    },
  },
  {
    engineerId: 'engSS20',
    name: 'Rachel Green',
    level: 4,
    currentTeamId: 'teamSS6',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['React Native', 'iOS', 'Android', 'Mobile CI/CD'],
      yearsOfExperience: 6,
    },
  },
  {
    engineerId: 'engSS21',
    name: 'Samwise Gamgee',
    level: 3,
    currentTeamId: 'teamSS6',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['React', 'Next.js', 'Web Performance', 'SSR'],
      yearsOfExperience: 5,
    },
  },
  {
    engineerId: 'engSS22',
    name: 'Tina Fey',
    level: 3,
    currentTeamId: 'teamSS6',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['UI/UX Design', 'Figma', 'Accessibility (a11y)'],
      yearsOfExperience: 4,
    },
  },
  {
    engineerId: 'engSS23',
    name: 'Umar Rashid',
    level: 2,
    currentTeamId: 'teamSS6',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['HTML/CSS', 'JavaScript', 'Design Systems'],
      yearsOfExperience: 2,
    },
  },
  // Team SS7: Merchant Guild (Seller)
  {
    engineerId: 'engSS24',
    name: 'James Brown',
    level: 4,
    currentTeamId: 'teamSS7',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Full-stack', 'React', 'Node.js', 'Seller Experience'],
      yearsOfExperience: 9,
    },
  },
  {
    engineerId: 'engSS25',
    name: 'Vera Chen',
    level: 3,
    currentTeamId: 'teamSS7',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Backend API', 'Java', 'SQL', 'Distributed Systems'],
      yearsOfExperience: 5,
    },
  },
  {
    engineerId: 'engSS26',
    name: 'Will Turner',
    level: 3,
    currentTeamId: 'teamSS7',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Frontend', 'Vue.js', 'Seller Portal UI'],
      yearsOfExperience: 4,
    },
  },
  {
    engineerId: 'engSS27',
    name: 'Xena Warrior',
    level: 2,
    currentTeamId: 'teamSS7',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['QA', 'Automation', 'Cypress', 'Selenium'],
      yearsOfExperience: 3,
    },
  },
  // Team SS8: Data Dragoons (Analytics)
  {
    engineerId: 'engSS28',
    name: 'Li Wang',
    level: 5,
    currentTeamId: 'teamSS8',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Data Architecture', 'Snowflake', 'DBT', 'Airflow'],
      yearsOfExperience: 12,
    },
  },
  {
    engineerId: 'engSS29',
    name: 'Yasmin Al-Jamil',
    level: 4,
    currentTeamId: 'teamSS8',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['Data Engineering', 'Spark', 'Kafka', 'Python'],
      yearsOfExperience: 7,
    },
  },
  {
    engineerId: 'engSS30',
    name: 'Zane Miller',
    level: 3,
    currentTeamId: 'teamSS8',
    attributes: {
      isAISWE: false,
      aiAgentType: null,
      skills: ['BI', 'Tableau', 'Looker', 'Advanced SQL'],
      yearsOfExperience: 4,
    },
  },
  // AI Engineers
  {
    engineerId: 'engSS-AI-1',
    name: 'AI-Search-Ranker (ShopSphere)',
    level: 5,
    currentTeamId: 'teamSS2',
    attributes: {
      isAISWE: true,
      aiAgentType: 'Search Relevance ML',
      skills: ['Vector Search', 'Learning to Rank', 'NLP'],
      yearsOfExperience: null,
    },
  },
  {
    engineerId: 'engSS-AI-2',
    name: 'AI-Fraud-Detector (ShopSphere)',
    level: 4,
    currentTeamId: 'teamSS5',
    attributes: {
      isAISWE: true,
      aiAgentType: 'Fraud Detection ML',
      skills: ['Anomaly Detection', 'Real-time Scoring', 'TensorFlow'],
      yearsOfExperience: null,
    },
  },
  {
    engineerId: 'engSS-AI-3',
    name: 'AI-Reco-Bot (ShopSphere)',
    level: 4,
    currentTeamId: 'teamSS3',
    attributes: {
      isAISWE: true,
      aiAgentType: 'Collaborative Filtering',
      skills: ['ML', 'Cold Start', 'Personalization'],
      yearsOfExperience: null,
    },
  },
  {
    engineerId: 'engSS-AI-4',
    name: 'AI-Support-Analyst (ShopSphere)',
    level: 3,
    currentTeamId: 'teamSS8',
    attributes: {
      isAISWE: true,
      aiAgentType: 'BI Automation',
      skills: ['SQL Generation', 'NLP Reporting', 'Tableau'],
      yearsOfExperience: null,
    },
  },
];

const shopSphereTeamsData = [
  {
    teamId: 'teamSS1',
    teamName: 'Atlas Infrastructure',
    teamIdentity: 'Atlas Infra',
    fundedHeadcount: 5,
    engineers: ['Anil Gupta', 'Bethany Smith', 'Carlos Diaz', 'Diana Wells'],
    awayTeamMembers: [],
    sdmId: 'sdmSS1',
    pmtId: 'pmtSS1',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 6,
      aiProductivityGainPercent: 10,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS2',
    teamName: 'Search Strikers',
    teamIdentity: 'Search Strikers',
    fundedHeadcount: 5,
    engineers: [
      'Maria Rodriguez',
      'Evan Li',
      'Fiona Chen',
      'George Kims',
      'AI-Search-Ranker (ShopSphere)',
    ],
    awayTeamMembers: [],
    sdmId: 'sdmSS2',
    pmtId: 'pmtSS2',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 5,
      aiProductivityGainPercent: 20,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS3',
    teamName: 'Discovery Crew',
    teamIdentity: 'Discovery Crew',
    fundedHeadcount: 4,
    engineers: ['Hannah Davis', 'Ivan Petrov', 'Julia Romano', 'AI-Reco-Bot (ShopSphere)'],
    awayTeamMembers: [],
    sdmId: 'sdmSS2',
    pmtId: 'pmtSS2',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 5,
      aiProductivityGainPercent: 25,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS4',
    teamName: 'Checkout Kings',
    teamIdentity: 'Checkout Kings',
    fundedHeadcount: 5,
    engineers: ['Kenji Watanabe', 'Leo Martinez', 'Mona Amini', 'Nate Jacobs'],
    awayTeamMembers: [],
    sdmId: 'sdmSS3',
    pmtId: 'pmtSS3',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 7,
      aiProductivityGainPercent: 10,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS5',
    teamName: 'Financial Operations',
    teamIdentity: 'FinOps',
    fundedHeadcount: 4,
    engineers: ['Oscar Wilde', 'Patel Kumar', 'Quincy Jones', 'AI-Fraud-Detector (ShopSphere)'],
    awayTeamMembers: [],
    sdmId: 'sdmSS3',
    pmtId: 'pmtSS3',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 8,
      aiProductivityGainPercent: 15,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS6',
    teamName: 'UI Engineering Wizards',
    teamIdentity: 'UIE Wizards',
    fundedHeadcount: 6,
    engineers: ['Emily White', 'Rachel Green', 'Samwise Gamgee', 'Tina Fey', 'Umar Rashid'],
    awayTeamMembers: [
      {
        awayMemberId: 'awaySS6_1',
        name: 'UXContractor-01',
        level: 3,
        sourceTeam: 'External Agency',
        attributes: {},
      },
    ],
    sdmId: 'sdmSS4',
    pmtId: 'pmtSS4',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 5,
      aiProductivityGainPercent: 15,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS7',
    teamName: 'Merchant Guild',
    teamIdentity: 'Merchant Guild',
    fundedHeadcount: 5,
    engineers: ['James Brown', 'Vera Chen', 'Will Turner', 'Xena Warrior'],
    awayTeamMembers: [],
    sdmId: 'sdmSS5',
    pmtId: 'pmtSS5',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 4,
      aiProductivityGainPercent: 5,
    },
    attributes: {},
  },
  {
    teamId: 'teamSS8',
    teamName: 'Data Dragoons',
    teamIdentity: 'Data Dragoons',
    fundedHeadcount: 4,
    engineers: ['Li Wang', 'Yasmin Al-Jamil', 'Zane Miller', 'AI-Support-Analyst (ShopSphere)'],
    awayTeamMembers: [],
    sdmId: 'sdmSS6',
    pmtId: 'pmtSS6',
    teamCapacityAdjustments: {
      leaveUptakeEstimates: [],
      variableLeaveImpact: {},
      teamActivities: [],
      avgOverheadHoursPerWeekPerSDE: 5,
      aiProductivityGainPercent: 20,
    },
    attributes: {},
  },
];

const sampleServicesDataShopSphere = [
  {
    serviceName: 'UserService',
    serviceDescription: 'Manages user accounts, authentication, profiles, and addresses.',
    owningTeamId: 'teamSS1',
    apis: [
      {
        apiName: 'AuthAPI',
        apiDescription: 'Handles user login and registration.',
        dependentApis: [],
        attributes: {},
      },
      {
        apiName: 'ProfileAPI',
        apiDescription: 'Manages user profile data.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: [],
    platformDependencies: ['AWS Cognito', 'AWS DynamoDB'],
    attributes: {},
  },
  {
    serviceName: 'ProductCatalogService',
    serviceDescription: 'Manages all product information, categories, and pricing.',
    owningTeamId: 'teamSS7',
    apis: [
      {
        apiName: 'ProductAPI',
        apiDescription: 'Get product details by SKU or ID.',
        dependentApis: [],
        attributes: {},
      },
      {
        apiName: 'CategoryAPI',
        apiDescription: 'Get products by category.',
        dependentApis: ['SearchService:SearchAPI'],
        attributes: {},
      },
    ],
    serviceDependencies: ['SellerPortalService'],
    platformDependencies: ['AWS S3', 'PostgreSQL'],
    attributes: {},
  },
  {
    serviceName: 'SearchService',
    serviceDescription: 'Provides product search, faceting, and typeahead.',
    owningTeamId: 'teamSS2',
    apis: [
      {
        apiName: 'SearchAPI',
        apiDescription: 'Main search query API.',
        dependentApis: [],
        attributes: {},
      },
      {
        apiName: 'TypeaheadAPI',
        apiDescription: 'Provides search suggestions.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: ['ProductCatalogService', 'IndexingService'],
    platformDependencies: ['Elasticsearch', 'Redis'],
    attributes: {},
  },
  {
    serviceName: 'IndexingService',
    serviceDescription: 'Consumes product updates and indexes them into the search engine.',
    owningTeamId: 'teamSS2',
    apis: [
      {
        apiName: 'UpdateIndexAPI',
        apiDescription: 'Receives updates to index.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: ['ProductCatalogService'],
    platformDependencies: ['Kafka', 'Elasticsearch'],
    attributes: {},
  },
  {
    serviceName: 'RecommendationService',
    serviceDescription: 'Generates personalized product recommendations.',
    owningTeamId: 'teamSS3',
    apis: [
      {
        apiName: 'RecommendationsAPI',
        apiDescription: 'Get recommendations for a user or product.',
        dependentApis: ['ProductCatalogService:ProductAPI', 'UserService:ProfileAPI'],
        attributes: {},
      },
    ],
    serviceDependencies: ['ProductCatalogService', 'UserService', 'AnalyticsPipelineService'],
    platformDependencies: ['AWS Sagemaker', 'Spark', 'S3'],
    attributes: {},
  },
  {
    serviceName: 'ShoppingCartService',
    serviceDescription: 'Manages user shopping carts.',
    owningTeamId: 'teamSS4',
    apis: [
      {
        apiName: 'CartAPI',
        apiDescription: 'Add, remove, and view cart items.',
        dependentApis: ['ProductCatalogService:ProductAPI'],
        attributes: {},
      },
    ],
    serviceDependencies: ['ProductCatalogService', 'UserService'],
    platformDependencies: ['Redis', 'DynamoDB'],
    attributes: {},
  },
  {
    serviceName: 'OrderService',
    serviceDescription: 'Manages the order lifecycle from creation to fulfillment.',
    owningTeamId: 'teamSS4',
    apis: [
      {
        apiName: 'CreateOrderAPI',
        apiDescription: 'Creates a new order.',
        dependentApis: [
          'ShoppingCartService:CartAPI',
          'PaymentService:ChargeAPI',
          'InventoryService:ReserveAPI',
        ],
        attributes: {},
      },
      {
        apiName: 'GetOrderAPI',
        apiDescription: 'Retrieves order status and details.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: [
      'ShoppingCartService',
      'PaymentService',
      'InventoryService',
      'NotificationService',
    ],
    platformDependencies: ['PostgreSQL', 'Kafka'],
    attributes: {},
  },
  {
    serviceName: 'PaymentService',
    serviceDescription: 'Handles all payment processing and fraud detection.',
    owningTeamId: 'teamSS5',
    apis: [
      {
        apiName: 'ChargeAPI',
        apiDescription: 'Processes a payment charge.',
        dependentApis: ['FraudDetectionService:AssessRiskAPI'],
        attributes: {},
      },
      {
        apiName: 'RefundAPI',
        apiDescription: 'Processes a refund.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: ['FraudDetectionService', 'UserService'],
    platformDependencies: ['Stripe Gateway', 'Adyen Gateway', 'AWS KMS'],
    attributes: {},
  },
  {
    serviceName: 'FraudDetectionService',
    serviceDescription: 'Provides real-time risk assessment for transactions.',
    owningTeamId: 'teamSS5',
    apis: [
      {
        apiName: 'AssessRiskAPI',
        apiDescription: 'Returns a risk score for a transaction.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: ['AnalyticsPipelineService'],
    platformDependencies: ['Internal ML Platform', 'Redis'],
    attributes: {},
  },
  {
    serviceName: 'SellerPortalService',
    serviceDescription: 'Frontend and backend for seller-facing tools.',
    owningTeamId: 'teamSS7',
    apis: [
      {
        apiName: 'ListingAPI',
        apiDescription: 'Allows sellers to create/update listings.',
        dependentApis: ['ProductCatalogService:ProductAPI'],
        attributes: {},
      },
    ],
    serviceDependencies: ['ProductCatalogService', 'AnalyticsPipelineService'],
    platformDependencies: ['React', 'Node.js', 'PostgreSQL'],
    attributes: {},
  },
  {
    serviceName: 'InventoryService',
    serviceDescription:
      'Manages stock levels for all products. (Mock, owned by external Fulfillment org)',
    owningTeamId: null, // No internal owner
    apis: [
      {
        apiName: 'ReserveAPI',
        apiDescription: 'Reserves stock for an order.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: [],
    platformDependencies: ['Oracle Fusion'],
    attributes: {},
  },
  {
    serviceName: 'NotificationService',
    serviceDescription: 'Sends emails, push, and SMS notifications. (Mock, owned by Core Platform)',
    owningTeamId: 'teamSS1', // Owned by Platform Infra
    apis: [
      {
        apiName: 'SendEmailAPI',
        apiDescription: 'Sends transactional emails.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: ['UserService'],
    platformDependencies: ['AWS SES', 'AWS SNS'],
    attributes: {},
  },
  {
    serviceName: 'AnalyticsPipelineService',
    serviceDescription: 'Collects and processes user and system events.',
    owningTeamId: 'teamSS8',
    apis: [
      {
        apiName: 'EventIngestAPI',
        apiDescription: 'Receives tracking events.',
        dependentApis: [],
        attributes: {},
      },
    ],
    serviceDependencies: [],
    platformDependencies: ['Kafka', 'Spark', 'Snowflake'],
    attributes: {},
  },
  {
    serviceName: 'WebGatewayService',
    serviceDescription: 'The main BFF (Backend-for-Frontend) for the ShopSphere website.',
    owningTeamId: 'teamSS6',
    apis: [
      {
        apiName: 'GraphQL API',
        apiDescription: 'Aggregates data for the web/mobile clients.',
        dependentApis: [
          'ProductCatalogService:ProductAPI',
          'SearchService:SearchAPI',
          'RecommendationService:RecommendationsAPI',
          'ShoppingCartService:CartAPI',
        ],
        attributes: {},
      },
    ],
    serviceDependencies: [
      'ProductCatalogService',
      'SearchService',
      'RecommendationService',
      'ShoppingCartService',
      'UserService',
    ],
    platformDependencies: ['Node.js', 'Apollo Server', 'Kubernetes'],
    attributes: {},
  },
];

const sampleYearlyInitiativesShopSphere = [
  // --- 2025 PROTECTED ---
  {
    initiativeId: 'init-ss-ktlo',
    title: 'KTLO / Operational Excellence',
    description: 'Ongoing bug fixes, security patches, library updates, performance tuning.',
    isProtected: true,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 1.0 },
      { teamId: 'teamSS2', sdeYears: 0.75 },
      { teamId: 'teamSS3', sdeYears: 0.5 },
      { teamId: 'teamSS4', sdeYears: 1.0 },
      { teamId: 'teamSS5', sdeYears: 1.0 },
      { teamId: 'teamSS6', sdeYears: 1.25 },
      { teamId: 'teamSS7', sdeYears: 0.75 },
      { teamId: 'teamSS8', sdeYears: 0.5 },
    ],
    impactedServiceIds: [],
    roi: { category: 'Tech Debt', valueType: 'QualitativeScore', estimatedValue: 'Critical' },
    targetDueDate: '2025-12-31',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-platform-resilience'],
    primaryGoalId: 'goal-ss-stability-2025',
    projectManager: null,
    owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
    technicalPOC: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Baseline KTLO for all teams.', planningYear: 2025 },
  },
  {
    initiativeId: 'init-ss-oncall',
    title: 'On-Call / Production Support',
    description: 'Dedicated capacity for handling live site issues and production incidents.',
    isProtected: true,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 1.0 },
      { teamId: 'teamSS2', sdeYears: 0.5 },
      { teamId: 'teamSS3', sdeYears: 0.5 },
      { teamId: 'teamSS4', sdeYears: 1.0 },
      { teamId: 'teamSS5', sdeYears: 0.75 },
      { teamId: 'teamSS6', sdeYears: 1.0 },
      { teamId: 'teamSS7', sdeYears: 0.5 },
      { teamId: 'teamSS8', sdeYears: 0.5 },
    ],
    impactedServiceIds: [],
    roi: { category: 'Ops Stability', valueType: 'QualitativeScore', estimatedValue: 'Critical' },
    targetDueDate: '2025-12-31',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-platform-resilience'],
    primaryGoalId: 'goal-ss-stability-2025',
    projectManager: null,
    owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
    technicalPOC: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Standard on-call rotation budget.', planningYear: 2025 },
  },
  {
    initiativeId: 'init-ss-pci',
    title: 'PCI-DSS 4.0 Compliance Audit & Remediation',
    description: 'Mandatory work to achieve and pass PCI-DSS 4.0 compliance.',
    isProtected: true,
    assignments: [
      { teamId: 'teamSS5', sdeYears: 1.5 },
      { teamId: 'teamSS4', sdeYears: 0.5 },
      { teamId: 'teamSS1', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['PaymentService', 'OrderService', 'UserService'],
    roi: { category: 'Compliance', valueType: 'QualitativeScore', estimatedValue: 'Mandatory' },
    targetDueDate: '2025-09-30',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-security-compliance'],
    primaryGoalId: 'goal-ss-security-2025',
    projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
    owner: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
    technicalPOC: { type: 'engineer', id: 'engOscarWilde_teamSS5_ss', name: 'Oscar Wilde' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Non-negotiable security work.', planningYear: 2025 },
  },
  // --- 2025 COMMITTED (ATL) ---
  {
    initiativeId: 'init-ss-001',
    title: 'AI-Powered Search (Vector Search POC)',
    description: 'POC to integrate vector-based search for image and semantic search.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS2', sdeYears: 1.5 },
      { teamId: 'teamSS3', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['SearchService', 'IndexingService', 'RecommendationService'],
    roi: {
      category: 'Innovation',
      valueType: 'MetricImprovement',
      estimatedValue: 'Explore new search revenue',
    },
    targetDueDate: '2025-07-31',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-ai-ml', 'theme-ss-conversion'],
    primaryGoalId: 'goal-ss-search-2025',
    projectManager: { type: 'projectManager', id: 'pmSS001', name: 'Marcus Timeline' },
    owner: { type: 'pmt', id: 'pmtSS2', name: 'Ben Carter' },
    technicalPOC: { type: 'sdm', id: 'sdmSS2', name: 'Maria Rodriguez' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'High-priority experiment.', planningYear: 2025 },
  },
  {
    initiativeId: 'init-ss-002',
    title: 'Implement "Buy Now, Pay Later" (BNPL) Integration',
    description: 'Integrate a third-party BNPL provider (e.g., Klarna, Affirm) into checkout.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS5', sdeYears: 1.0 },
      { teamId: 'teamSS4', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['PaymentService', 'OrderService', 'WebGatewayService'],
    roi: {
      category: 'Revenue Generation',
      valueType: 'MetricImprovement',
      estimatedValue: 'Est. +2% Conversion',
    },
    targetDueDate: '2025-06-30',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-conversion', 'theme-ss-feature'],
    primaryGoalId: 'goal-ss-conversion-2025',
    projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
    owner: { type: 'pmt', id: 'pmtSS3', name: 'Priya Singh' },
    technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Key Q2 revenue goal.', planningYear: 2025 },
  },
  {
    initiativeId: 'init-ss-003',
    title: 'Mobile App Performance Overhaul (React Native)',
    description: 'Refactor core app screens to improve TTI and reduce crashes by 50%.',
    isProtected: false,
    assignments: [{ teamId: 'teamSS6', sdeYears: 2.0 }],
    impactedServiceIds: ['WebGatewayService'],
    roi: {
      category: 'User Experience',
      valueType: 'MetricImprovement',
      estimatedValue: '-50% Crash Rate',
    },
    targetDueDate: '2025-10-31',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-ux-perf', 'theme-ss-platform-resilience'],
    primaryGoalId: 'goal-ss-conversion-2025',
    projectManager: { type: 'projectManager', id: 'pmSS001', name: 'Marcus Timeline' },
    owner: { type: 'pmt', id: 'pmtSS4', name: 'Alex Johnson' },
    technicalPOC: { type: 'sdm', id: 'sdmSS4', name: 'Emily White' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Major focus for UIE team.', planningYear: 2025 },
  },
  {
    initiativeId: 'init-ss-004',
    title: 'Seller Self-Service Ad Platform (v1)',
    description: 'Allow sellers to purchase and manage sponsored product placements.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS7', sdeYears: 1.5 },
      { teamId: 'teamSS8', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['SellerPortalService', 'AnalyticsPipelineService', 'SearchService'],
    roi: {
      category: 'Revenue Generation',
      valueType: 'Monetary',
      estimatedValue: '5M New Revenue',
    },
    targetDueDate: '2025-11-30',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-seller-success', 'theme-ss-revenue'],
    primaryGoalId: 'goal-ss-seller-2025',
    projectManager: { type: 'projectManager', id: 'pmSS003', name: 'Kenji Velocity' },
    owner: { type: 'pmt', id: 'pmtSS5', name: 'Zoe Kim' },
    technicalPOC: { type: 'sdm', id: 'sdmSS5', name: 'James Brown' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'New revenue stream.', planningYear: 2025 },
  },
  {
    initiativeId: 'init-ss-005',
    title: 'Kubernetes Platform Migration (Phase 1)',
    description: 'Migrate legacy VM-based services (UserService, OrderService) to EKS.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 1.5 },
      { teamId: 'teamSS4', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['UserService', 'OrderService'],
    roi: {
      category: 'Tech Debt',
      valueType: 'CostReduction',
      estimatedValue: 'Reduce compute cost 20%',
    },
    targetDueDate: '2025-12-31',
    actualCompletionDate: null,
    status: 'Committed',
    themes: ['theme-ss-platform-resilience', 'theme-ss-cost'],
    primaryGoalId: 'goal-ss-stability-2025',
    projectManager: null,
    owner: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
    technicalPOC: { type: 'engineer', id: 'engBethanySmith_teamSS1_ss', name: 'Bethany Smith' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Key infra goal.', planningYear: 2025 },
  },
  // --- 2025 BACKLOG (BTL) ---
  {
    initiativeId: 'init-ss-006',
    title: 'Real-time Inventory Check',
    description: 'Move from 15-min batch inventory updates to real-time checks at Add-to-Cart.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS4', sdeYears: 1.0 },
      { teamId: 'teamSS1', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['ShoppingCartService', 'InventoryService', 'OrderService'],
    roi: {
      category: 'User Experience',
      valueType: 'MetricImprovement',
      estimatedValue: 'Reduce oversell incidents',
    },
    targetDueDate: '2025-11-15',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-ux-perf', 'theme-ss-platform-resilience'],
    primaryGoalId: 'goal-ss-conversion-2025',
    projectManager: null,
    owner: { type: 'pmt', id: 'pmtSS3', name: 'Priya Singh' },
    technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
    workPackageIds: [],
    attributes: {
      pmCapacityNotes: 'High engineering complexity due to external service.',
      planningYear: 2025,
    },
  },
  {
    initiativeId: 'init-ss-007',
    title: 'Automated Seller Payouts',
    description:
      'Build automated daily payouts for sellers instead of manual monthly wire transfers.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS7', sdeYears: 1.0 },
      { teamId: 'teamSS5', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['SellerPortalService', 'PaymentService'],
    roi: {
      category: 'Seller Success',
      valueType: 'QualitativeScore',
      estimatedValue: 'High Seller SAT',
    },
    targetDueDate: '2025-10-31',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-seller-success'],
    primaryGoalId: 'goal-ss-seller-2025',
    projectManager: null,
    owner: { type: 'pmt', id: 'pmtSS5', name: 'Zoe Kim' },
    technicalPOC: { type: 'sdm', id: 'sdmSS5', name: 'James Brown' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'High demand from sellers.', planningYear: 2025 },
  },
  // --- 2026 (3YP / BACKLOG) ---
  {
    initiativeId: 'init-ss-008',
    title: 'Expand to EU Market (GDPR & Payments)',
    description:
      'Launch ShopSphere in Germany/France, requiring GDPR compliance and EU payment methods.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 1.5 },
      { teamId: 'teamSS5', sdeYears: 1.0 },
      { teamId: 'teamSS4', sdeYears: 1.0 },
      { teamId: 'teamSS6', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['UserService', 'PaymentService', 'OrderService', 'WebGatewayService'],
    roi: { category: 'Strategic', valueType: 'MarketExpansion', estimatedValue: 'EU Market Entry' },
    targetDueDate: '2026-06-30',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-revenue', 'theme-ss-security-compliance'],
    primaryGoalId: 'goal-ss-expansion-2026',
    projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
    owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
    technicalPOC: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Major strategic push for 2026.', planningYear: 2026 },
  },
  {
    initiativeId: 'init-ss-009',
    title: 'Live Video Shopping (POC)',
    description: 'POC for influencers to host live video streams to sell products.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS6', sdeYears: 1.0 },
      { teamId: 'teamSS7', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['WebGatewayService', 'SellerPortalService'],
    roi: {
      category: 'Innovation',
      valueType: 'Narrative',
      estimatedValue: 'Explore new shopping paradigm',
    },
    targetDueDate: '2026-03-31',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-feature', 'theme-ss-ai-ml'],
    primaryGoalId: 'goal-ss-conversion-2025',
    projectManager: null,
    owner: { type: 'pmt', id: 'pmtSS4', name: 'Alex Johnson' },
    technicalPOC: { type: 'sdm', id: 'sdmSS4', name: 'Emily White' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'R&D project.', planningYear: 2026 },
  },
  {
    initiativeId: 'init-ss-010',
    title: 'Carbon-Neutral Fulfillment Pipeline',
    description: 'Track and offset carbon emissions for all orders.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS8', sdeYears: 1.0 },
      { teamId: 'teamSS4', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['AnalyticsPipelineService', 'OrderService'],
    roi: { category: 'Strategic', valueType: 'QualitativeScore', estimatedValue: 'ESG Goal' },
    targetDueDate: '2026-12-31',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-platform-resilience'],
    primaryGoalId: 'goal-ss-esg-2026',
    projectManager: { type: 'projectManager', id: 'pmSS003', name: 'Kenji Velocity' },
    owner: { type: 'sdm', id: 'sdmSS6', name: 'Li Wang' },
    technicalPOC: { type: 'sdm', id: 'sdmSS6', name: 'Li Wang' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Company-wide ESG initiative.', planningYear: 2026 },
  },
  {
    initiativeId: 'init-ss-011',
    title: 'Warehouse Automation Integration (POC)',
    description:
      'POC to integrate with fulfillment center robotics for real-time stock and order status.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 1.0 },
      { teamId: 'teamSS7', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['InventoryService', 'OrderService', 'SellerPortalService'],
    roi: {
      category: 'Innovation',
      valueType: 'CostReduction',
      estimatedValue: 'Future fulfillment efficiency',
    },
    targetDueDate: '2026-09-30',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-cost', 'theme-ss-ai-ml'],
    primaryGoalId: 'goal-ss-stability-2025',
    projectManager: null,
    owner: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
    technicalPOC: { type: 'engineer', id: 'engBethanySmith_teamSS1_ss', name: 'Bethany Smith' },
    workPackageIds: [],
    attributes: {
      pmCapacityNotes: 'Explore integration with new automated warehouses.',
      planningYear: 2026,
    },
  },
  {
    initiativeId: 'init-ss-012',
    title: 'ShopSphere Prime (v1)',
    description:
      'Design and launch a "Prime" subscription for free shipping and exclusive benefits.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS4', sdeYears: 1.5 },
      { teamId: 'teamSS5', sdeYears: 1.0 },
      { teamId: 'teamSS6', sdeYears: 1.0 },
      { teamId: 'teamSS1', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['OrderService', 'PaymentService', 'WebGatewayService', 'UserService'],
    roi: { category: 'Revenue Generation', valueType: 'Monetary', estimatedValue: '20M New ARR' },
    targetDueDate: '2026-11-30',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-revenue', 'theme-ss-feature'],
    primaryGoalId: 'goal-ss-revenue-2026',
    projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
    owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
    technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Major new revenue stream for 2026.', planningYear: 2026 },
  },
  // --- 2027 (3YP / FUTURE) ---
  {
    initiativeId: 'init-ss-013',
    title: 'Headless Commerce Platform (Phase 1)',
    description: 'Begin migrating to a fully headless architecture, decoupling all frontends.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 2.0 },
      { teamId: 'teamSS6', sdeYears: 1.5 },
      { teamId: 'teamSS2', sdeYears: 0.5 },
    ],
    impactedServiceIds: ['WebGatewayService', 'SearchService', 'ProductCatalogService'],
    roi: {
      category: 'Tech Debt',
      valueType: 'Productivity/Efficiency',
      estimatedValue: 'Enable faster feature dev',
    },
    targetDueDate: '2027-12-31',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-platform-resilience', 'theme-ss-ux-perf'],
    primaryGoalId: 'goal-ss-platform-2027',
    projectManager: { type: 'projectManager', id: 'pmSS001', name: 'Marcus Timeline' },
    owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
    technicalPOC: { type: 'sdm', id: 'sdmSS4', name: 'Emily White' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Major multi-year architectural shift.', planningYear: 2027 },
  },
  {
    initiativeId: 'init-ss-014',
    title: 'Hyper-Personalization Engine (v2)',
    description: 'Move beyond recommendations to a fully personalized DOM and user journey.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS3', sdeYears: 2.0 },
      { teamId: 'teamSS8', sdeYears: 1.0 },
      { teamId: 'teamSS6', sdeYears: 1.0 },
    ],
    impactedServiceIds: ['RecommendationService', 'AnalyticsPipelineService', 'WebGatewayService'],
    roi: {
      category: 'Innovation',
      valueType: 'MetricImprovement',
      estimatedValue: 'NPS +10 points',
    },
    targetDueDate: '2027-09-30',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-ai-ml', 'theme-ss-conversion'],
    primaryGoalId: 'goal-ss-search-2025',
    projectManager: null,
    owner: { type: 'pmt', id: 'pmtSS2', name: 'Ben Carter' },
    technicalPOC: { type: 'engineer', id: 'engHannahDavis_teamSS3_ss', name: 'Hannah Davis' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Long-term AI-driven vision.', planningYear: 2027 },
  },
  {
    initiativeId: 'init-ss-015',
    title: 'Expand to LATAM Market',
    description: 'Launch ShopSphere in Brazil and Mexico.',
    isProtected: false,
    assignments: [
      { teamId: 'teamSS1', sdeYears: 1.0 },
      { teamId: 'teamSS5', sdeYears: 1.5 },
    ],
    impactedServiceIds: ['UserService', 'PaymentService', 'OrderService'],
    roi: {
      category: 'Strategic',
      valueType: 'MarketExpansion',
      estimatedValue: 'LATAM Market Entry',
    },
    targetDueDate: '2027-12-31',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-revenue'],
    primaryGoalId: 'goal-ss-expansion-2027',
    projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
    owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
    technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
    workPackageIds: [],
    attributes: { pmCapacityNotes: 'Follow-on from EU expansion.', planningYear: 2027 },
  },
  {
    initiativeId: 'init-ss-016',
    title: 'Service Mesh Implementation',
    description: 'Roll out a full service mesh (e.g., Istio) for all microservices.',
    isProtected: false,
    assignments: [{ teamId: 'teamSS1', sdeYears: 2.0 }],
    impactedServiceIds: [],
    roi: {
      category: 'Tech Debt',
      valueType: 'Productivity/Efficiency',
      estimatedValue: 'Standardize observability',
    },
    targetDueDate: '2027-06-30',
    actualCompletionDate: null,
    status: 'Backlog',
    themes: ['theme-ss-platform-resilience'],
    primaryGoalId: 'goal-ss-platform-2027',
    projectManager: null,
    owner: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
    technicalPOC: { type: 'engineer', id: 'engBethanySmith_teamSS1_ss', name: 'Bethany Smith' },
    workPackageIds: [],
    attributes: {
      pmCapacityNotes: 'Improve security, observability, and traffic management.',
      planningYear: 2027,
    },
  },
];

// Then, the main sampleSystemDataShopSphere object
const sampleSystemDataShopSphere = {
  systemName: 'ShopSphere',
  systemDescription:
    'ShopSphere is a large-scale eCommerce platform, handling everything from product search and discovery to checkout and seller management.',
  seniorManagers: sampleSeniorManagersDataShopSphere,
  teams: shopSphereTeamsData,
  sdms: shopSphereSDMsData,
  pmts: shopSpherePMTsData,
  projectManagers: sampleProjectManagersDataShopSphere,
  services: sampleServicesDataShopSphere,
  platformDependencies: [],
  capacityConfiguration: {
    workingDaysPerYear: 261,
    standardHoursPerDay: 8,
    globalConstraints: {
      publicHolidays: 12,
      orgEvents: [
        { id: 'eventSS001', name: 'Annual Hackathon', estimatedDaysPerSDE: 2, attributes: {} },
        {
          id: 'eventSS002',
          name: 'Company All-Hands (Quarterly)',
          estimatedDaysPerSDE: 1,
          attributes: {},
        }, // 0.25 * 4
      ],
    },
    leaveTypes: [
      { id: 'annual_ss', name: 'Annual Leave', defaultEstimatedDays: 25, attributes: {} },
      { id: 'sick_ss', name: 'Sick Leave', defaultEstimatedDays: 10, attributes: {} },
      { id: 'study_ss', name: 'Study Leave', defaultEstimatedDays: 5, attributes: {} },
      { id: 'inlieu_ss', name: 'Time off In-lieu Leave', defaultEstimatedDays: 2, attributes: {} },
    ],
    attributes: {},
  },
  yearlyInitiatives: sampleYearlyInitiativesShopSphere,
  goals: [
    {
      goalId: 'goal-ss-stability-2025',
      name: 'Platform Resilience & Stability 2025',
      description:
        'Ensure 99.99% uptime for critical services (Checkout, Payments) and reduce tech debt.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
      projectManager: { type: 'projectManager', id: 'pmSS001', name: 'Marcus Timeline' },
      technicalPOC: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
      initiativeIds: [
        'init-ss-ktlo',
        'init-ss-oncall',
        'init-ss-005',
        'init-ss-010',
        'init-ss-011',
      ],
      attributes: {},
      dueDate: '2025-12-31',
    },
    {
      goalId: 'goal-ss-security-2025',
      name: 'Achieve Security & Compliance Goals 2025',
      description:
        'Pass all mandatory compliance audits (PCI 4.0) and remediate critical vulnerabilities.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
      projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
      technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
      initiativeIds: ['init-ss-pci', 'init-ss-008'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-conversion-2025',
      name: 'Increase Checkout Conversion by 5% 2025',
      description:
        'Improve the user experience from discovery to payment to increase conversion rate.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
      projectManager: { type: 'projectManager', id: 'pmSS001', name: 'Marcus Timeline' },
      technicalPOC: { type: 'sdm', id: 'sdmSS4', name: 'Emily White' },
      initiativeIds: ['init-ss-002', 'init-ss-003', 'init-ss-006', 'init-ss-009', 'init-ss-013'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-search-2025',
      name: 'Improve Search & Discovery 2025',
      description: 'Leverage AI/ML to improve search relevance and product discovery.',
      strategyLink: null,
      owner: { type: 'pmt', id: 'pmtSS2', name: 'Ben Carter' },
      projectManager: null,
      technicalPOC: { type: 'sdm', id: 'sdmSS2', name: 'Maria Rodriguez' },
      initiativeIds: ['init-ss-001', 'init-ss-014'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-seller-2025',
      name: 'Grow Seller Platform Adoption by 20% 2025',
      description: 'Enhance seller tools to attract and retain more merchants.',
      strategyLink: null,
      owner: { type: 'pmt', id: 'pmtSS5', name: 'Zoe Kim' },
      projectManager: { type: 'projectManager', id: 'pmSS003', name: 'Kenji Velocity' },
      technicalPOC: { type: 'sdm', id: 'sdmSS5', name: 'James Brown' },
      initiativeIds: ['init-ss-004', 'init-ss-007'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-expansion-2026',
      name: 'Launch in EU Market 2026',
      description: 'Strategic goal to launch ShopSphere in Germany and France by end of 2026.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
      projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
      technicalPOC: { type: 'sdm', id: 'sdmSS1', name: 'Anil Gupta' },
      initiativeIds: ['init-ss-008'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-revenue-2026',
      name: 'Launch New Revenue Streams 2026',
      description: 'Launch ShopSphere Prime subscription program.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
      projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
      technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
      initiativeIds: ['init-ss-012'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-esg-2026',
      name: 'Meet ESG Commitments 2026',
      description: 'Fulfill company-wide Environmental, Social, and Governance commitments.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
      projectManager: { type: 'projectManager', id: 'pmSS003', name: 'Kenji Velocity' },
      technicalPOC: { type: 'sdm', id: 'sdmSS6', name: 'Li Wang' },
      initiativeIds: ['init-ss-010'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-platform-2027',
      name: 'Evolve to Headless Platform 2027',
      description: 'Decouple frontend experiences from backend services to increase dev velocity.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS1', name: 'Sarah Chen' },
      projectManager: { type: 'projectManager', id: 'pmSS001', name: 'Marcus Timeline' },
      technicalPOC: { type: 'sdm', id: 'sdmSS4', name: 'Emily White' },
      initiativeIds: ['init-ss-013', 'init-ss-016'],
      attributes: {},
      dueDate: null,
    },
    {
      goalId: 'goal-ss-expansion-2027',
      name: 'Expand to LATAM Market 2027',
      description: 'Launch ShopSphere in Brazil and Mexico.',
      strategyLink: null,
      owner: { type: 'seniorManager', id: 'srMgrSS2', name: 'David Lee' },
      projectManager: { type: 'projectManager', id: 'pmSS002', name: 'Chloe Scope' },
      technicalPOC: { type: 'sdm', id: 'sdmSS3', name: 'Kenji Watanabe' },
      initiativeIds: ['init-ss-015'],
      attributes: {},
      dueDate: null,
    },
  ],
  definedThemes: [
    {
      themeId: 'theme-ss-platform-resilience',
      name: 'Platform Resilience',
      description: 'Work related to stability, scalability, and tech debt reduction.',
      relatedGoalIds: ['goal-ss-stability-2025', 'goal-ss-platform-2027', 'goal-ss-esg-2026'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-security-compliance',
      name: 'Security & Compliance',
      description: 'Mandatory security, privacy, and compliance work (e.g., PCI, GDPR).',
      relatedGoalIds: ['goal-ss-security-2025', 'goal-ss-expansion-2026'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-conversion',
      name: 'Conversion Optimization',
      description: 'Features directly aimed at improving the checkout conversion rate.',
      relatedGoalIds: ['goal-ss-conversion-2025', 'goal-ss-search-2025', 'goal-ss-platform-2027'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-ux-perf',
      name: 'UX & Performance',
      description: 'Improving the frontend user experience and app performance.',
      relatedGoalIds: ['goal-ss-conversion-2025', 'goal-ss-platform-2027'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-ai-ml',
      name: 'AI/ML Innovation',
      description: 'Leveraging AI and Machine Learning for new features.',
      relatedGoalIds: ['goal-ss-search-2025', 'goal-ss-stability-2025', 'goal-ss-conversion-2025'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-seller-success',
      name: 'Seller Success',
      description: 'Building tools and features for third-party sellers.',
      relatedGoalIds: ['goal-ss-seller-2025'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-revenue',
      name: 'New Revenue Streams',
      description: 'Initiatives that create new lines of revenue (e.g., Ads, new markets).',
      relatedGoalIds: [
        'goal-ss-seller-2025',
        'goal-ss-expansion-2026',
        'goal-ss-revenue-2026',
        'goal-ss-expansion-2027',
      ],
      attributes: {},
    },
    {
      themeId: 'theme-ss-feature',
      name: 'New Product Feature',
      description: 'General new features for customers.',
      relatedGoalIds: ['goal-ss-conversion-2025', 'goal-ss-revenue-2026'],
      attributes: {},
    },
    {
      themeId: 'theme-ss-cost',
      name: 'Cost Reduction',
      description: 'Initiatives focused on reducing infrastructure or operational costs.',
      relatedGoalIds: ['goal-ss-stability-2025'],
      attributes: {},
    },
  ],
  archivedYearlyPlans: [],
  workPackages: [],
  calculatedCapacityMetrics: null,
  allKnownEngineers: sampleAllKnownEngineersShopSphere,
  attributes: {},
};
